language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pycodestyle api
  - pycodestyle tests
  - pytest --cov=api
  - coverage report -m
after_success:
 - codecov
