language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database flask_api_test;' -U postgres
script:
  - pycodestyle api
  - pycodestyle tests
  - pytest --cov=api
  - coverage report -m
after_success:
 - codecov
