"""empty message

Revision ID: 1c713a67a1e5
Revises: None
Create Date: 2019-08-07 02:23:58.335764

"""

# revision identifiers, used by Alembic.
revision = '1c713a67a1e5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('contract_value', sa.Float(precision=16, asdecimal=True, decimal_return_scale=2), nullable=False),
    sa.Column('percentage_return', sa.Float(precision=16, asdecimal=True, decimal_return_scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=16, asdecimal=True, decimal_return_scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
