"""empty message

Revision ID: 6faf2c8721dc
Revises: 1c713a67a1e5
Create Date: 2019-08-07 14:01:35.806502

"""

# revision identifiers, used by Alembic.
revision = '6faf2c8721dc'
down_revision = '1c713a67a1e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bids_user_email_fkey', 'bids', type_='foreignkey')
    op.drop_constraint('bids_project_id_fkey', 'bids', type_='foreignkey')
    op.create_foreign_key(None, 'bids', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bids', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.create_foreign_key('bids_project_id_fkey', 'bids', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('bids_user_email_fkey', 'bids', 'users', ['user_email'], ['email'])
    # ### end Alembic commands ###
