"""empty message

Revision ID: a664eb62d003
Revises: 6faf2c8721dc
Create Date: 2019-08-07 14:15:39.086444

"""

# revision identifiers, used by Alembic.
revision = 'a664eb62d003'
down_revision = '6faf2c8721dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_user_email_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_email_fkey', 'projects', 'users', ['user_email'], ['email'])
    # ### end Alembic commands ###
